import type { MailRepository } from '@/shared/mail/mailRepository'

const notAvailable = (): never => {
  throw new Error('Mail backend is not available in web mode. Use the Electron desktop target.')
}

export const webMailRepository: MailRepository = {
  listAccounts: notAvailable,
  createAccount: notAvailable,
  testAccountConnection: notAvailable,
  deleteAccount: notAvailable,
  listFolders: notAvailable,
  createFolder: notAvailable,
  renameFolder: notAvailable,
  deleteFolder: notAvailable,
  listMessages: notAvailable,
  getDraft: notAvailable,
  searchMessages: notAvailable,
  listLabels: notAvailable,
  getMessage: notAvailable,
  addLabel: notAvailable,
  removeLabel: notAvailable,
  renameLabel: notAvailable,
  deleteLabel: notAvailable,
  saveDraft: notAvailable,
  sendMessage: notAvailable,
  toggleStar: notAvailable,
  toggleRead: notAvailable,
  batchToggleRead: notAvailable,
  deleteMessage: notAvailable,
  batchDeleteMessages: notAvailable,
  archiveMessage: notAvailable,
  restoreMessage: notAvailable,
  moveMessage: notAvailable,
  batchMoveMessages: notAvailable,
  markAllRead: notAvailable,
  syncAccount: notAvailable,
  getMailboxBundle: notAvailable,
  getAttachmentContent: notAvailable,
  getAccountConfig: notAvailable,
  updateAccount: notAvailable,
  getAccountQuota: notAvailable,
  listOAuthProviders: notAvailable,
  authorizeOAuth: notAvailable,
  listContacts: notAvailable,
  createContact: notAvailable,
  updateContact: notAvailable,
  deleteContact: notAvailable,
  searchContacts: notAvailable,
  listContactGroups: notAvailable,
  createContactGroup: notAvailable,
  updateContactGroup: notAvailable,
  deleteContactGroup: notAvailable,
  uploadContactAvatar: notAvailable,
  deleteContactAvatar: notAvailable,
  getContactAvatar: notAvailable,
  getSecurityStatus: notAvailable,
  unlockStorage: notAvailable,
  setMasterPassword: notAvailable,
  clearMasterPassword: notAvailable,
  lockCurrentSession: notAvailable,
  getStorageDir: notAvailable,
}
