use crate::models::{
    AttachmentMeta, MailFolderKind, MailMessage, MailThread, MailboxFolder,
};

pub fn default_folders_for_account(account_id: &str) -> Vec<MailboxFolder> {
    vec![
        folder(
            &format!("inbox-{account_id}"),
            account_id,
            "Inbox",
            MailFolderKind::Inbox,
            0,
            0,
            "mdi-inbox-arrow-down",
        ),
        folder(
            &format!("starred-{account_id}"),
            account_id,
            "Starred",
            MailFolderKind::Starred,
            0,
            0,
            "mdi-star-outline",
        ),
        folder(
            &format!("sent-{account_id}"),
            account_id,
            "Sent",
            MailFolderKind::Sent,
            0,
            0,
            "mdi-send-outline",
        ),
        folder(
            &format!("drafts-{account_id}"),
            account_id,
            "Drafts",
            MailFolderKind::Drafts,
            0,
            0,
            "mdi-file-document-edit-outline",
        ),
        folder(
            &format!("trash-{account_id}"),
            account_id,
            "Trash",
            MailFolderKind::Trash,
            0,
            0,
            "mdi-delete-outline",
        ),
    ]
}

pub fn seeded_folders() -> Vec<MailboxFolder> {
    vec![
        folder(
            "inbox-work",
            "acc-work",
            "Inbox",
            MailFolderKind::Inbox,
            4,
            24,
            "mdi-inbox-arrow-down",
        ),
        folder(
            "starred-work",
            "acc-work",
            "Starred",
            MailFolderKind::Starred,
            1,
            5,
            "mdi-star-outline",
        ),
        folder(
            "sent-work",
            "acc-work",
            "Sent",
            MailFolderKind::Sent,
            0,
            12,
            "mdi-send-outline",
        ),
        folder(
            "drafts-work",
            "acc-work",
            "Drafts",
            MailFolderKind::Drafts,
            0,
            2,
            "mdi-file-document-edit-outline",
        ),
        folder(
            "trash-work",
            "acc-work",
            "Trash",
            MailFolderKind::Trash,
            0,
            1,
            "mdi-delete-outline",
        ),
        folder(
            "inbox-personal",
            "acc-personal",
            "Inbox",
            MailFolderKind::Inbox,
            3,
            15,
            "mdi-inbox-arrow-down",
        ),
        folder(
            "starred-personal",
            "acc-personal",
            "Starred",
            MailFolderKind::Starred,
            1,
            3,
            "mdi-star-outline",
        ),
        folder(
            "sent-personal",
            "acc-personal",
            "Sent",
            MailFolderKind::Sent,
            0,
            8,
            "mdi-send-outline",
        ),
        folder(
            "drafts-personal",
            "acc-personal",
            "Drafts",
            MailFolderKind::Drafts,
            0,
            1,
            "mdi-file-document-edit-outline",
        ),
        folder(
            "trash-personal",
            "acc-personal",
            "Trash",
            MailFolderKind::Trash,
            0,
            0,
            "mdi-delete-outline",
        ),
    ]
}

pub fn seeded_threads() -> Vec<MailThread> {
    vec![
        MailThread {
            id: "thread-1".into(),
            account_id: "acc-work".into(),
            subject: "Milestone review for Linux MVP".into(),
            message_ids: vec!["msg-1".into()],
            last_message_at: "2026-03-12T08:15:00.000Z".into(),
            unread_count: 1,
        },
        MailThread {
            id: "thread-2".into(),
            account_id: "acc-work".into(),
            subject: "Material You palette options".into(),
            message_ids: vec!["msg-2".into()],
            last_message_at: "2026-03-12T07:25:00.000Z".into(),
            unread_count: 0,
        },
        MailThread {
            id: "thread-3".into(),
            account_id: "acc-work".into(),
            subject: "IMAP bridge spike notes".into(),
            message_ids: vec!["msg-3".into()],
            last_message_at: "2026-03-11T18:42:00.000Z".into(),
            unread_count: 1,
        },
        MailThread {
            id: "thread-4".into(),
            account_id: "acc-personal".into(),
            subject: "Dinner on Friday?".into(),
            message_ids: vec!["msg-4".into()],
            last_message_at: "2026-03-12T06:10:00.000Z".into(),
            unread_count: 1,
        },
        MailThread {
            id: "thread-5".into(),
            account_id: "acc-personal".into(),
            subject: "Flight receipt attached".into(),
            message_ids: vec!["msg-5".into()],
            last_message_at: "2026-03-11T22:30:00.000Z".into(),
            unread_count: 0,
        },
    ]
}

pub fn seeded_messages() -> Vec<MailMessage> {
    vec![
        MailMessage {
            id: "msg-1".into(),
            account_id: "acc-work".into(),
            folder_id: "inbox-work".into(),
            thread_id: "thread-1".into(),
            subject: "Milestone review for Linux MVP".into(),
            preview: "The shell, routing, and Vuetify theme pass look ready for the first review.".into(),
            body: "<p>Hi team,</p><p>The Linux-first desktop shell is ready for review. We now have the three-pane layout, mock multi-account flows, and a dynamic Material You inspired theme seeded from user color preferences.</p><p>For the next slice, I recommend wiring the inbox list through the desktop mail bridge so the repository boundary stays stable while we replace mocks later.</p><p>— Rowan</p>".into(),
            from: "Rowan Patel".into(),
            from_email: "rowan@mailstack.dev".into(),
            to: vec!["hello@mailstack.dev".into()],
            cc: vec!["design@mailstack.dev".into()],
            sent_at: "2026-03-12T08:15:00.000Z".into(),
            received_at: "2026-03-12T08:15:00.000Z".into(),
            is_read: false,
            is_starred: true,
            has_attachments: false,
            attachments: vec![],
            labels: vec!["MVP".into()],
        },
        MailMessage {
            id: "msg-2".into(),
            account_id: "acc-work".into(),
            folder_id: "inbox-work".into(),
            thread_id: "thread-2".into(),
            subject: "Material You palette options".into(),
            preview: "Sharing two seed colors that feel balanced on both light and dark surfaces.".into(),
            body: "<p>I tested violet and teal as seed colors. Violet feels stronger for work mail, while teal keeps the reader calmer for longer sessions.</p><p>We can expose the seed as a user preference and persist only the seed plus density mode.</p>".into(),
            from: "Ava Kim".into(),
            from_email: "ava@mailstack.dev".into(),
            to: vec!["hello@mailstack.dev".into()],
            cc: vec![],
            sent_at: "2026-03-12T07:25:00.000Z".into(),
            received_at: "2026-03-12T07:25:00.000Z".into(),
            is_read: true,
            is_starred: false,
            has_attachments: false,
            attachments: vec![],
            labels: vec!["Theme".into()],
        },
        MailMessage {
            id: "msg-3".into(),
            account_id: "acc-work".into(),
            folder_id: "inbox-work".into(),
            thread_id: "thread-3".into(),
            subject: "IMAP bridge spike notes".into(),
            preview: "Attached are the protocol notes and rough command boundaries we discussed.".into(),
            body: "<p>I mapped the protocol layer into provider::imap, provider::smtp, and sync orchestration. We can keep commands narrow and return serde-aligned domain structs back to the UI.</p>".into(),
            from: "Noah Silva".into(),
            from_email: "noah@mailstack.dev".into(),
            to: vec!["hello@mailstack.dev".into()],
            cc: vec![],
            sent_at: "2026-03-11T18:42:00.000Z".into(),
            received_at: "2026-03-11T18:42:00.000Z".into(),
            is_read: false,
            is_starred: false,
            has_attachments: true,
            attachments: vec![AttachmentMeta {
                id: "att-1".into(),
                file_name: "imap-spike.pdf".into(),
                mime_type: "application/pdf".into(),
                size_bytes: 58_231,
            }],
            labels: vec!["Protocol".into()],
        },
        MailMessage {
            id: "msg-4".into(),
            account_id: "acc-personal".into(),
            folder_id: "inbox-personal".into(),
            thread_id: "thread-4".into(),
            subject: "Dinner on Friday?".into(),
            preview: "Still good for noodles this Friday night?".into(),
            body: "<p>Hey,</p><p>Are you still free for dinner on Friday? I found a new noodle place near the station.</p><p>— Lin</p>".into(),
            from: "Lin".into(),
            from_email: "lin@example.com".into(),
            to: vec!["iscccc@example.com".into()],
            cc: vec![],
            sent_at: "2026-03-12T06:10:00.000Z".into(),
            received_at: "2026-03-12T06:10:00.000Z".into(),
            is_read: false,
            is_starred: false,
            has_attachments: false,
            attachments: vec![],
            labels: vec![],
        },
        MailMessage {
            id: "msg-5".into(),
            account_id: "acc-personal".into(),
            folder_id: "sent-personal".into(),
            thread_id: "thread-5".into(),
            subject: "Flight receipt attached".into(),
            preview: "Forwarding the receipt in case you need it for reimbursement.".into(),
            body: "<p>Sending the flight receipt over now. Let me know if you also need the hotel invoice.</p>".into(),
            from: "iscccc".into(),
            from_email: "iscccc@example.com".into(),
            to: vec!["travel@example.com".into()],
            cc: vec![],
            sent_at: "2026-03-11T22:30:00.000Z".into(),
            received_at: "2026-03-11T22:30:00.000Z".into(),
            is_read: true,
            is_starred: true,
            has_attachments: true,
            attachments: vec![AttachmentMeta {
                id: "att-2".into(),
                file_name: "receipt.pdf".into(),
                mime_type: "application/pdf".into(),
                size_bytes: 22_104,
            }],
            labels: vec!["Travel".into()],
        },
    ]
}

fn folder(
    id: &str,
    account_id: &str,
    name: &str,
    kind: MailFolderKind,
    unread_count: u32,
    total_count: u32,
    icon: &str,
) -> MailboxFolder {
    MailboxFolder {
        id: id.into(),
        account_id: account_id.into(),
        name: name.into(),
        kind,
        unread_count,
        total_count,
        icon: icon.into(),
    }
}
